### ISSUE TITLE
Not getting any output using this action.

### ISSUE THREAD

**Issue by ayushi469** [mkumatag/container-image-updater-action#1]
Hey, I was trying your action `mkumatag/container-image-updater-action@v1.0.5` , but not getting any output like 'true' or 'false' as a 
output. 
 
```
name: update image when upstream is updated

on:
  push:
    branches: 
      - auto-update
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      need_update: ${{ steps.check.outputs.need_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{github.actor }}
            password: ${{ secrets.SECRET_TOKEN }}
- name: Check if update available
   id: check
   uses: mkumatag/container-image-updater-action@v1.0.5
   with:
       base-image: library/ubuntu:20.04
       image: ghcr.io/<user-name>/<repo-name>/<image-name>:latest
       image-reg-username: ${{ github.actor }}
       image-reg-password: ${{ secrets.SECRET_TOKEN }}

 - name: check for any update
   run: echo "${{steps.check.outputs.need_update}}"

```
output:
![echo](https://github.com/mkumatag/container-image-updater-action/assets/54853686/8f5db74c-3cf8-4810-907d-3e61df546ea7)

**Comment by mkumatag** [comment]
Its the hypen(-) not underscore(_) and also `s` is missing in the end, can you check after modifying to `needs-update`?

**Comment by ayushi469** [comment]
name: update image when upstream is updats

on:
  push:
    branches: 
      - auto-update
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-update: ${{ steps.check.outputs.needs-update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.SECRET_TOKEN }}

      - name: Check if update available
        id: check
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: library/ubuntu:20.04
          image: ghcr.io/ayushi-gupta2001/testing-branch/auto-update:latest
          image-reg-username: ${{ github.actor }}
          image-reg-password: ${{ secrets.SECRET_TOKEN }}

      - name: check if there is any update
        run: echo "${{steps.check.outputs.needs-update}}"
  
  update:
    needs: check
    runs-on: ubuntu-latest
    if: needs.check.outputs.needs-update.result == 'true'
    steps: 
      - run: echo "Need to update Image! ${{needs.check.outputs.needs-update.result}}"

  no_update_value:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.needs-update.result == 'false'
    steps: 
      - run: echo "No need to update ${{needs.check.outputs.needs-update.result}}"
      
I was checking with this code and checking, if there is any update then it should return an echo statement but my jobs "update" and "no-update" are skipped.

**Comment by ayushi469** [comment]
And does this tool always shows you "true" output? Because even after running it multiple times this GitHub action code, it is always showing me a "true" result not a "false" result.

**Comment by mkumatag** [comment]
for that your image mentioned here `ghcr.io/ayushi-gupta2001/testing-branch/auto-update:latest` should have the latest updated base image

**Comment by ayushi469** [comment]
Can you tell me, How can I make this GitHub action for multiple docker images? I have 10 docker image in my GitHub container registry and I want to check on a daily basis that those docker images are up-to-date. How can I list out all the docker images that I have on the GitHub container registry and how will I fetch base images of my custom docker image and how can I implement this situation to this GitHub-action?

**Comment by mkumatag** [comment]
https://github.com/mkumatag/container-image-updater-action-test/blob/main/.github/workflows/update.yaml is the sample workflow talks about using this action and below is the chatgtp generated code for multiple images

```yaml
name: check container images

on:
  schedule:
    - cron:  '0 0 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  hello_world_job:
    strategy:
      matrix:
        image: ['mkumatag/hello-world', 'mkumatag/another-image']
    runs-on: ubuntu-latest
    name: Check if container image update required
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Container Image Updater
        id: check
        uses: mkumatag/container-image-updater-action@v1.0.5
        with:
          base-image: 'registry.access.redhat.com/ubi8/ubi-minimal:latest'
          image: ${{ env.REGISTRY }}/${{ matrix.image }}:latest

      - name: Image update
        run: echo "Image update required for ${{ matrix.image }}: ${{ steps.check.outputs.needs-update }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ matrix.image }}:latest
        if: steps.check.outputs.needs-update == 'true'
```

> Note: untested code

**Comment by ayushi469** [comment]
can't we modify our base image as well? like something using like ${{ matrix.baseImage }}?

**Comment by mkumatag** [comment]
> can't we modify our base image as well? like something using like ${{ matrix.baseImage }}?

chatgtp suggests this for that

```
env:
  REGISTRY: ghcr.io
  BASE_IMAGE_HELLO_WORLD: registry.access.redhat.com/ubi8/ubi-minimal:latest
  BASE_IMAGE_ANOTHER_IMAGE: my-registry/another-base-image:latest
```

```
- name: Container Image Updater
  id: check
  uses: mkumatag/container-image-updater-action@v1.0.5
  with:
    base-image: ${{ env['BASE_IMAGE_' + matrix.image.replace('-', '_').upper()] }}
    image: ${{ env.REGISTRY }}/${{ matrix.image }}:latest
```
